# SonarCloud Configuration
sonar.projectKey=Albanezfxp_authShield
sonar.organization=albanezfxp

# Project Info
sonar.projectName=authShield - Task Manager with Auth
sonar.projectVersion=1.0.0
sonar.sourceEncoding=UTF-8

# Source Code
sonar.sources=auth_project_backend/src,auth_project_frontend/src

# Exclusões
sonar.exclusions=**/*.spec.ts,**/*.test.ts,**/node_modules/**,**/dist/**,**/build/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
# ⚠️ REMOVIDO (deprecated / pode causar comportamento estranho)
# sonar.lang.patterns.ts=**/*.ts,**/*.tsx
# sonar.lang.patterns.js=

# Coverage
sonar.coverage.exclusions=**/*.spec.ts,**/*.test.ts,**/node_modules/**


# Backend
sonar.typescript.node.maxBodyLength=250

# Quality Gate
sonar.qualitygate.wait=false
sonar.qualitygate.timeout=300