# SonarCloud Configuration
sonar.projectKey=Albanezfxp_authShield
sonar.organization=albanezfxp

# Project Info
sonar.projectName=authShield - Task Manager with Auth
sonar.projectVersion=1.0.0
sonar.sourceEncoding=UTF-8

# Source Code
sonar.sources=auth_project_backend/src,auth_project_frontend/src

# Exclusões de Análise (Arquivos que não devem ser analisados pelo Sonar)
sonar.exclusions=**/*.spec.ts,**/*.test.ts,**/*.test.tsx,**/node_modules/**,**/dist/**,**/build/**

# CORREÇÃO: Caminho do relatório de cobertura ajustado para a pasta do Frontend no Monorepo
sonar.javascript.lcov.reportPaths=auth_project_frontend/coverage/lcov.info

# Exclusões de Cobertura (Garante que os arquivos de teste não abaixem a sua média de % de cobertura)
sonar.coverage.exclusions=auth_project_backend/src/**/*.spec.ts,auth_project_frontend/src/**/*.test.ts,auth_project_frontend/src/**/*.test.tsx,auth_project_frontend/src/test/test-utils/**

# Backend Configurations
sonar.typescript.node.maxBodyLength=250

# Quality Gate
sonar.qualitygate.wait=false
sonar.qualitygate.timeout=300