FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache dumb-init

COPY package*.json ./

RUN npm install

COPY . .

RUN npx prisma generate
RUN npm run build

EXPOSE 3333

ENTRYPOINT ["dumb-init", "--"]

CMD ["node", "dist/src/main.js"]